### ISSUE TITLE
API Inquiry

### ISSUE THREAD

**Issue by MasterJames** [fvdm/nodejs-foscam#5]
**Hi I was wondering if there is a way to upload video to FTP in the Specs for "IP Camera" API?**
If not, who is responsible for making this grievous oversight that I can inquire further about making it part of the next version?
Like is there a consortium like the Kronos Group or what have you/we for this?

This was the best I found from Foscam, has FTP but nothing about Video uploads?
http://www.foscam.es/descarga/ipcam_cgi_sdk.pdf

Also this seemed as good or better, similar...
http://gurau-audibert.hd.free.fr/josdblog/wp-content/uploads/2013/09/DCS-910920_CGI_v1-20.pdf
but no settings for video upload in the spec I guess (if there even is agreement on this somewhere)?

This PDF seems fairly useful with Streaming Protocols?
ftp://planet.com.ru/support_soft/IPsurvilence/SDK_API_hm131/IP%20Camera%20Standard%20API%20%20Interface%20Specification%20v2%2003%20_2010-04-09_.pdf

This has nothing with FTP at all
https://dash.evercam.io/swagger

It really has to be a specification in a globally agreed API somewhere, even if 'restful' because the motion detection triggers the uploading, so the remaining options of streaming and or probing for all files seems like an wanted and undesirable overload to the network.
It seems obvious that you would want the repeated shorter video clips sent to a cheap FTP off-site location as fast as possible during detection (with pre-lap, frame rate, settings etc.).

As a work-around I can only imagine another computer with local NAS with everything stored that has custom software that receives an email notification and then knows to pick the current video for upload but again inefficient?
Is there any good IP security cameras on the market that have open source firmware or better yet scripts? Complex scripts on detection etc. would be also a wise thing for the manufacturers to add.

**Comment by fvdm** [comment]
I think you better ask [Foscam](http://www.foscam.com/company/contact-us.html) themselves when it comes to camera features and their API specs. My Node.js module is not and neither am I in any way affiliated to Foscam Co, so I can not help you with that.

What I do know is that my Tenvis camera (based on Foscam spec) can upload motion triggered recordings to a remote FTP host. Is that what you are looking for?

**Comment by MasterJames** [comment]
Okay good to know thanks.
So there's no official consortium that defines this IP Camera Spec?
What kind of Video Format does it upload to FTP?

**Comment by fvdm** [comment]
I just found out my camera uploads only JPG stills with FTP. I never noticed that before because I let my NAS take care of motion/audio triggers and recording with Surveillance Station.

Regarding your consortium question, I can only find [Onvif](http://www.onvif.org/). They maintain standards for camera installation and communication. I believe Foscam camera's produced in the last couple of years are ONVIF compatible.

**Comment by MasterJames** [comment]
Okay thanks. BTW 
Foscam told me they rebranded to Amcrest.com

**Comment by fvdm** [comment]
Good to know, thanks

**Comment by MasterJames** [comment]
This seems to not limit what can be uploaded via FTP.

http://www.onvif.org/specs/srv/act/ONVIF-ActionEngine-Service-Spec-v100.pdf

But it's not clear in the spec to set anything like length of video clips or type maybe I'll look deeper for a media type like MP4 etc. 

The problem with Amcrest is they only upload via FTP an encrypted DAV format which is pretty disfunctional.
I thought I saw a forum discussion about changing it a few months ago, but it's a firmware issue and I fear they are more so being greedy about it affecting their cloud service sales.
If they accessed the FTP as a view source then you could convert to MP4 but that's more of a hack then allowing users to choose a prefered/usable format for FTP upload.
They also need a browser plugin which is sooo 2014.
I'm still inquiring if you can do both ftp and SD card but their videos of their interface suggest otherwise.

Nice to see someone is doing the right thing here with JS. There's a lot of compitition in this space if I was any one of them I'd be hiring you to build a modern solution.
Anyway open source is the future they'd be smart to that with their legacy Mashup code too. I say Mashup because you need on average 4 programs to access all these settings etc. when you include browser plug-ins and DAV conversion tools etc. Every one of these companies is about 3 years behind and made a real mess of things.
